### ISSUE TITLE
Change config path to absolute path

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/dart_runner_digitization#3]
Config path is currently a relative path, which means the script will not work if run in a different directory. Change to an absolute path.

**Comment by helrond** [comment]
(I think it's the other way around - the config path is currently relative, but it should be absolute)

**Comment by bonniegee** [comment]
@helrond I am struggling a lot with this for some reason--do I want to do some variation of `Path("local_settings.cfg").absolute()`?

**Comment by helrond** [comment]
Take a look at https://stackoverflow.com/questions/3430372/how-do-i-get-the-full-path-of-the-current-files-directory
